"""empty message

Revision ID: 1ce6f4db43ca
Revises: 7b37999975bb
Create Date: 2019-10-22 11:44:26.877790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce6f4db43ca'
down_revision = '7b37999975bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchase', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase', 'purchase_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'status_id')
    op.drop_table('purchase_status')
    # ### end Alembic commands ###
