"""empty message

Revision ID: 7b37999975bb
Revises: 6113b10b428a
Create Date: 2019-10-17 12:02:00.833165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b37999975bb'
down_revision = '6113b10b428a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'total')
    # ### end Alembic commands ###
